/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;
import NapakalakiGame.DeathBadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;
import NapakalakiGame.TreasureKind;
import java.util.ArrayList;

/**
 *
 * @author Elena María Gómez Ríos y Jose Luis Martinez Ortiz
 */
public class BadConsequenceView extends javax.swing.JPanel {
    BadConsequence badConsequenceModel;
    
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
        jLText.setLineWrap(true);
        jLText.setAutoscrolls(false);
        jLText.setWrapStyleWord(true);
        jLText.setBackground(getBackground());
        
        jLOcultos.setLineWrap(true);
        jLOcultos.setAutoscrolls(false);
        jLOcultos.setWrapStyleWord(true);
        jLOcultos.setBackground(getBackground());

        jLVisibles.setLineWrap(true);
        jLVisibles.setAutoscrolls(false);
        jLVisibles.setWrapStyleWord(true);
        jLVisibles.setBackground(getBackground());
    }
    
     public void setBadConsequence (BadConsequence bc){
        badConsequenceModel = bc;
        jLText.setText(badConsequenceModel.getText());
        jLevels.setText("Niveles: "+badConsequenceModel.getLevels()); 
        
        String visibles="";
        String ocultos="";
        String muerte="";
        
        if (bc instanceof SpecificBadConsequence){
            ArrayList<TreasureKind> vi = ((SpecificBadConsequence)bc).getSpecificVisibleTreasures();
            if (!vi.isEmpty())
                visibles+="Tesoros Visibles: ";
            for (TreasureKind elemento: vi){
                visibles+=elemento+" ";
            }
            
            ArrayList<TreasureKind> hi = ((SpecificBadConsequence)bc).getSpecificHiddenTreasures();
            if (!hi.isEmpty())
                ocultos+="Tesoros Ocultos: ";
            for (TreasureKind elemento: hi){
                ocultos+=elemento+" ";
            }
        }else{
            visibles="Tesoros Visibles: "+((NumericBadConsequence)bc).getNVisibleTreasures();
            ocultos="Tesoros Ocultos: "+((NumericBadConsequence)bc).getNHiddenTreasures();
            if (bc instanceof DeathBadConsequence)
                muerte="Muerte";          
        }
        
            
        jLVisibles.setText(visibles);
        jLOcultos.setText(ocultos);
        jLMuerte.setText(muerte);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLevels = new javax.swing.JLabel();
        jLMuerte = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLOcultos = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLVisibles = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bad Consequence"));

        jLevels.setText("Niveles");

        jLMuerte.setText("Muerte");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLText.setEditable(false);
        jLText.setColumns(10);
        jLText.setRows(3);
        jLText.setAutoscrolls(false);
        jScrollPane1.setViewportView(jLText);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLOcultos.setEditable(false);
        jLOcultos.setColumns(20);
        jLOcultos.setRows(1);
        jScrollPane2.setViewportView(jLOcultos);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLVisibles.setEditable(false);
        jLVisibles.setColumns(20);
        jLVisibles.setRows(1);
        jScrollPane3.setViewportView(jLVisibles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLevels)
                        .addGap(104, 104, 104)
                        .addComponent(jLMuerte)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLevels)
                    .addComponent(jLMuerte))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLMuerte;
    private javax.swing.JTextArea jLOcultos;
    private javax.swing.JTextArea jLText;
    private javax.swing.JTextArea jLVisibles;
    private javax.swing.JLabel jLevels;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
