/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.CombatResult;
import NapakalakiGame.Napakalaki;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author elena
 */
public class NapakalakiView extends JFrame {
    Napakalaki napakalakiModel;
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xSize = ((int) tk.getScreenSize().getWidth());
        int ySize = ((int) tk.getScreenSize().getHeight());
        setSize(xSize,ySize);
        setResizable(false);
        setLocation(0,0);
        jBCombat.setEnabled(false);
        jBNextTurn.setEnabled(false);
    }
    
    public void setNapakalaki(Napakalaki n){
        napakalakiModel= n;
        
        playerView.setPlayer(napakalakiModel.getCurrentPlayer());
        monsterView.setMonster(napakalakiModel.getCurrentMonster());
        playerView.setNapakalaki(napakalakiModel);
        monsterView.setVisible(false);
        playerView.isVisiblePendingBadConsequence();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerView = new GUI.PlayerView();
        monsterView = new GUI.MonsterView();
        jBMeetMonster = new javax.swing.JButton();
        jBCombat = new javax.swing.JButton();
        jBNextTurn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(playerView);
        playerView.setBounds(12, 12, 596, 693);
        getContentPane().add(monsterView);
        monsterView.setBounds(614, 12, 650, 430);

        jBMeetMonster.setText("Meet the Monster");
        jBMeetMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMeetMonsterActionPerformed(evt);
            }
        });
        getContentPane().add(jBMeetMonster);
        jBMeetMonster.setBounds(662, 485, 220, 29);

        jBCombat.setText("Combat");
        jBCombat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCombatActionPerformed(evt);
            }
        });
        getContentPane().add(jBCombat);
        jBCombat.setBounds(662, 532, 220, 29);

        jBNextTurn.setText("Next Turn");
        jBNextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNextTurnActionPerformed(evt);
            }
        });
        getContentPane().add(jBNextTurn);
        jBNextTurn.setBounds(662, 579, 220, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNextTurnActionPerformed
        if (napakalakiModel.getCurrentPlayer().validState()){
            napakalakiModel.nextTurn();
            jBMeetMonster.setEnabled(true);
            jBCombat.setEnabled(false);
            jBNextTurn.setEnabled(false);
            playerView.setEnabledjBStealTreasure(false);
            //Actualiza la vista
            setNapakalaki(napakalakiModel);
        }
    }//GEN-LAST:event_jBNextTurnActionPerformed

    private void jBMeetMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMeetMonsterActionPerformed
        monsterView.setVisible(true);
        jBCombat.setEnabled(true);
        playerView.setEnabledjBMakeVisible(false);
        jBMeetMonster.setEnabled(false);
    }//GEN-LAST:event_jBMeetMonsterActionPerformed

    private void jBCombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCombatActionPerformed
        CombatResult resultado;
        resultado = napakalakiModel.developCombat();
        String texto = "";
        
        
        switch(resultado){
            case WIN: texto = "Has Ganado";break;
            case LOSE:texto = "Has Perdido";break;
            case LOSEANDCONVERT:texto = "Te combiertes en sectario";break;
            case WINGAME: texto = "Has Ganado el juego";break;
        }
        JOptionPane.showMessageDialog(this,texto,"Resultado",JOptionPane.PLAIN_MESSAGE);
        
        
        playerView.setEnabledjBMakeVisible(true);
        jBNextTurn.setEnabled(true);
        jBCombat.setEnabled(false);
        playerView.isEnabledjBStealTreasure();
        playerView.isVisiblePendingBadConsequence();
        //Actualiza la vista
        setNapakalaki(napakalakiModel);
    }//GEN-LAST:event_jBCombatActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCombat;
    private javax.swing.JButton jBMeetMonster;
    private javax.swing.JButton jBNextTurn;
    private GUI.MonsterView monsterView;
    private GUI.PlayerView playerView;
    // End of variables declaration//GEN-END:variables
}
