/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;
import NapakalakiGame.DeathBadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;
import NapakalakiGame.TreasureKind;
import java.util.ArrayList;

/**
 *
 * @author Elena María Gómez Ríos, Jose Luis Martínez Ortiz
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {
    BadConsequence pendingBCModel;
    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
        jLOcultos.setLineWrap(true);
        jLOcultos.setAutoscrolls(false);
        jLOcultos.setWrapStyleWord(true);
        jLOcultos.setBackground(getBackground());

        jLVisibles.setLineWrap(true);
        jLVisibles.setAutoscrolls(false);
        jLVisibles.setWrapStyleWord(true);
        jLVisibles.setBackground(getBackground());
    }
    
    public void setPendingBadConsequenceView(BadConsequence bc){
        pendingBCModel = bc;
        String visibles = "";
        String ocultos = "";
        if (bc instanceof SpecificBadConsequence){
            ArrayList<TreasureKind> vi = ((SpecificBadConsequence)bc).getSpecificVisibleTreasures();
            if (!vi.isEmpty())
                visibles+="Tesoros Visibles: ";
            for (TreasureKind elemento: vi){
                visibles+=elemento+" ";
            }
            
            ArrayList<TreasureKind> hi = ((SpecificBadConsequence)bc).getSpecificHiddenTreasures();
            if (!hi.isEmpty())
                ocultos+="Tesoros Ocultos: ";
            for (TreasureKind elemento: hi){
                ocultos+=elemento+" ";
            }
        }else{
            visibles="Tesoros Visibles: "+((NumericBadConsequence)bc).getNVisibleTreasures();
            ocultos="Tesoros Ocultos: "+((NumericBadConsequence)bc).getNHiddenTreasures();
    
        }
        
            
        jLVisibles.setText(visibles);
        jLOcultos.setText(ocultos);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jLVisibles = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLOcultos = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pending Bad Consequence"));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLVisibles.setEditable(false);
        jLVisibles.setColumns(20);
        jLVisibles.setRows(1);
        jScrollPane3.setViewportView(jLVisibles);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLOcultos.setEditable(false);
        jLOcultos.setColumns(20);
        jLOcultos.setRows(1);
        jScrollPane4.setViewportView(jLOcultos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jLOcultos;
    private javax.swing.JTextArea jLVisibles;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
