/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.JTextField;

/**
 *
 * @author elena
 */
public class PlayerNamesCapture extends javax.swing.JDialog {
    private ArrayList<String> names;
    
    private ArrayList <JLabel> labels;
    private ArrayList <JTextField> texts;
    private int numeroPlayers=2;

    /**
     * Creates new form PlayerNamesCapture
     */
    public PlayerNamesCapture(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        names = new ArrayList();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        });
        jBPlay.setEnabled(false);
        
        ((DefaultEditor)jSNJugadores.getEditor()).getTextField().setEditable(false);
        ((DefaultEditor)jSNJugadores.getEditor()).getTextField().setHorizontalAlignment(JTextField.CENTER);
        
        labels = new ArrayList();
        labels.add(jLabel3);
        labels.add(jLabel4);
        
        texts = new ArrayList();
        texts.add(jTplayer3);
        texts.add(jTplayer4);
        
        setVisiblePlayers(2);
    }
    
    private void setVisiblePlayers (int numero){     
        for (int i=0; i<=(numero-3); i++){
            labels.get(i).setVisible(true);
            texts.get(i).setVisible(true);
        }
        for (int i=numero-2; i<labels.size(); i++){
            labels.get(i).setVisible(false);
            texts.get(i).setVisible(false);
            texts.get(i).setText("");
        }

    }
    
    private void datosVacios(){
        boolean estado = true;
        if(jTplayer1.getText().length()!=0 &&
                jTplayer2.getText().length()!=0){
            for(int i=0; i<= numeroPlayers-3 && estado;i++){
                estado = (texts.get(i).getText().length() != 0);
            }         
        }else{
            estado=false;
        }
        
        jBPlay.setEnabled(estado);

    }
    
    //Comprobamos que los nombres de los jugadores sean distintos, para evitar
    //errores en el juego
    public boolean nombresErroneos(){   
        ArrayList<String> nom= new ArrayList();
        boolean repetidos=false;
        nom.add(jTplayer1.getText());
        nom.add(jTplayer2.getText());
        for(int i=0; i<= numeroPlayers-3 ;i++){
            nom.add(texts.get(i).getText());
        }
        

        for (int i=0; i<nom.size()-1 && !repetidos; i++){
            for (int j=i+1; j<nom.size(); j++){
                if (nom.get(i).equals(nom.get(j))){
                    JOptionPane.showMessageDialog(this,"No puede haber jugadores con el mismo nombre","ERROR",JOptionPane.PLAIN_MESSAGE);
                    repetidos=true;
                }
            }
        }
        
        return repetidos;
    }
    
    
    public ArrayList<String> getNames(){
        this.setVisible(true);
        return names;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTplayer1 = new javax.swing.JTextField();
        jTplayer2 = new javax.swing.JTextField();
        jTplayer3 = new javax.swing.JTextField();
        jBPlay = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        jLNumeroJugadores = new javax.swing.JLabel();
        jSNJugadores = new javax.swing.JSpinner();
        jTplayer4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nombres de Jugadores");

        jLabel1.setText("Player 1");

        jLabel2.setText("Player 2");

        jLabel3.setText("Player 3");

        jTplayer1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTplayer1KeyReleased(evt);
            }
        });

        jTplayer2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTplayer2KeyReleased(evt);
            }
        });

        jTplayer3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTplayer3KeyReleased(evt);
            }
        });

        jBPlay.setText("Play");
        jBPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlayActionPerformed(evt);
            }
        });

        jBCancel.setText("Cancel");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        jLNumeroJugadores.setText("Selecciona el número de jugadores: ");

        jSNJugadores.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jSNJugadores.setModel(new javax.swing.SpinnerNumberModel(2, 2, 4, 1));
        jSNJugadores.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSNJugadoresStateChanged(evt);
            }
        });

        jTplayer4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTplayer4KeyReleased(evt);
            }
        });

        jLabel4.setText("Player 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTplayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTplayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTplayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jBPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jBCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLNumeroJugadores)
                                .addGap(18, 18, 18)
                                .addComponent(jSNJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTplayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumeroJugadores)
                    .addComponent(jSNJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTplayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTplayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTplayer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTplayer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPlay)
                    .addComponent(jBCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBCancelActionPerformed

    private void jBPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPlayActionPerformed
        if (!nombresErroneos()){
        
            names.add(jTplayer1.getText());
            names.add(jTplayer2.getText());
            for(int i=0; i<= numeroPlayers-3 ;i++){
                names.add(texts.get(i).getText());
            }
            dispose();
        }
    }//GEN-LAST:event_jBPlayActionPerformed

    private void jTplayer1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTplayer1KeyReleased
        datosVacios(); 
    }//GEN-LAST:event_jTplayer1KeyReleased

    private void jTplayer2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTplayer2KeyReleased
        datosVacios(); 
    }//GEN-LAST:event_jTplayer2KeyReleased

    private void jTplayer3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTplayer3KeyReleased
        datosVacios(); 
    }//GEN-LAST:event_jTplayer3KeyReleased

    private void jTplayer4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTplayer4KeyReleased
        datosVacios(); 
    }//GEN-LAST:event_jTplayer4KeyReleased

    private void jSNJugadoresStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSNJugadoresStateChanged
        numeroPlayers = (int)jSNJugadores.getModel().getValue();
        setVisiblePlayers(numeroPlayers);
        datosVacios();
    }//GEN-LAST:event_jSNJugadoresStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBPlay;
    private javax.swing.JLabel jLNumeroJugadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jSNJugadores;
    private javax.swing.JTextField jTplayer1;
    private javax.swing.JTextField jTplayer2;
    private javax.swing.JTextField jTplayer3;
    private javax.swing.JTextField jTplayer4;
    // End of variables declaration//GEN-END:variables
}
